export default [
  { value: "newwho", label: "New Who" },
  { value: "classic", label: "Classic Who" },
  { value: "general", label: "Általános" },
  { value: "torchwood", label: "Torchwood" },
  { value: "bigfinish", label: "Big Finish" },
  { value: "dwhaudio", label: "DWH Audio" },
  { value: "one", label: "Első Doktor" },
  { value: "two", label: "Második Doktor" },
  { value: "three", label: "Harmadik Doktor" },
  { value: "four", label: "Negyedik Doktor" },
  { value: "five", label: "Ötödik Doktor" },
  { value: "six", label: "Hatodik Doktor" },
  { value: "seven", label: "Hetedik Doktor" },
  { value: "eight", label: "Nyolcadik Doktor" },
  { value: "war", label: "War Doktor" },
  { value: "nine", label: "Kilencedik Doktor" },
  { value: "ten", label: "Tizedik Doktor" },
  { value: "eleven", label: "Tizenegyedik Doktor" },
  { value: "twelve", label: "Tizenkettedik Doktor" },
  { value: "thirteen", label: "Tizenharmadik Doktor" },
  { value: "fourteen", label: "Tizennegyedik Doktor" },
  { value: "fifteen", label: "Tizenötödik Doktor" }
];
